export default {
  User_1: {
    tags: [ 'poker' ],
    preference: [ 'male', 'bisexual' ],
    fname: 'User_1',
    lname: 'skiles',
    login: 'User_1',
    isFilled: true,
    age: 22,
    rating: 0,
    gender: 'male',
    biography: '123',
    images: [{src: "https://i.ibb.co/sgwqj1R/f824d53e3ffa.png", index: 0}],
    avatar: 0,
    location: { y: 37.5420654, x: 55.808093 },
  },
  User_2: { 
    tags: [ 'poker', 'food' ],
    preference: [ 'male', 'bisexual' ],
    fname: 'User_2',
    lname: 'skiles',
    login: 'User_2',
    isFilled: true,
    age: 22,
    rating: 0,
    gender: 'bisexual',
    biography: '123',
    images: [{src: "https://i.ibb.co/sgwqj1R/f824d53e3ffa.png", index: 0}],
    avatar: 0,
    location: { y: 37.5420654, x: 55.808093 },
  },
  User_3: {
    tags: [ 'poker', 'food', 'sex' ],
    preference: [ 'male', 'bisexual' ],
    fname: 'User_3',
    lname: 'skiles',
    login: 'User_3',
    isFilled: true,
    age: 22,
    rating: 0,
    gender: 'bisexual',
    biography: '123',
    images: [{src: "https://i.ibb.co/sgwqj1R/f824d53e3ffa.png", index: 0}],
    avatar: 0,
    
    location: { y: 37.5420654, x: 55.808093 },
  },
  User_5: {
    tags: [ 'poker', 'food' ],
    preference: [ 'male', 'bisexual' ],
    fname: 'User_5',
    lname: 'skiles',
    login: 'User_5',
    isFilled: true,
    age: 22,
    rating: 0,
    gender: 'bisexual',
    biography: '123',
    images: [{src: "https://i.ibb.co/sgwqj1R/f824d53e3ffa.png", index: 0}],
    avatar: 0,
    location: { y: 37.5420654, x: 55.808093 },
  },
  User_6: {
    tags: [ 'poker', 'food' ],
    preference: [ 'male', 'bisexual' ],
    fname: 'User_6',
    lname: 'skiles',
    login: 'User_6',
    isFilled: true,
    age: 22,
    rating: 0,
    gender: 'bisexual',
    biography: '123',
    images: [{src: "https://i.ibb.co/sgwqj1R/f824d53e3ffa.png", index: 0}],
    avatar: 0,
    location: { y: 37.5420654, x: 55.808093 },
  },
  User_7: {
    tags: [ 'poker', 'food' ],
    preference: [ 'male' ],
    fname: 'User_7',
    lname: 'skiles',
    login: 'User_7',
    isFilled: true,
    age: 23,
    rating: 0,
    gender: 'bisexual',
    biography: '123',
    images: [{src: "https://i.ibb.co/sgwqj1R/f824d53e3ffa.png", index: 0}],
    avatar: 0,
    location: { y: 37.5420654, x: 55.808093 },
  }
}